export { default as Login } from "./Login/Login"
export { default as Booking } from "./Booking/Booking"
export { default as ChooseAccount } from "./ChooseAccount/ChooseAccount"
export { default as ForgotPassword } from "./ForgotPassword/ForgotPassword"
export { default as Home } from "./Home/Home"
export { default as Profile } from "./Profile/Profile"
export { default as Register } from "./Register/Register"
export { default as SetPassword } from "./SetPassword/SetPassword"
